### ISSUE TITLE
Json decoder error

### ISSUE THREAD

**Issue by iwatobipen** [MolecularAI/maize-contrib#3]
Dear Developper,

Thanks for developping such as useful package for cheminformatics!
I found issue of maize-contrib with vina docking.
When I run the docking with vina from maize-contrib I got follwoing error.

File "/Users/pen/opt/anaconda3/envs/maize/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/kzfm/opt/anaconda3/envs/maize/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

The error occured when I use meeko ver 0.5. And when I used meeko 0.4.x it worked well.
yml file requred meeko >= 0.5
So I think this is an issue of the maize-contrib.
Thanks,

@iwatobipen

**Comment by halx** [comment]
I can't give you any further help but your input JSON is not syntactically correct.

**Comment by marco-chimfarm** [comment]
@iwatobipen Hi!

How did you fix this issue? I am having the exact same problem at random times

**Comment by iwatobipen** [comment]
What version of meeko are you using?

**Comment by marco-chimfarm** [comment]
Sorry, I did not give enough details in my question. I am not using Autodock, I am using Schrodinger's Ligprep and Glide to dock compounds.

However I get the same issue as you do, with the JSON decoder giving the error "Expecting value: line 2 column 1 (char 1)" at random times. Some runs go smothly, others are killed prematurely.

**Comment by rwxayheee** [comment]
Hi @iwatobipen 

Were you able to resolve this issue by upgrading to the most recent version? Or is it a new issue only with the current version of Meeko? 

Could you provide the JSON string (file) and the exact step related to Meeko that you think was triggering the error? 

@marco-chimfarm If possible, could you provide a sample JSON string (file) that gave you this error?

**Comment by marcobICR** [comment]
Hi Amy,

Unfortunately I don't have the JSON file that caused the issue. The issue is happening at random times, sometimes the same exact run will be completely fine. My first thought was that the docking waas not able to dock any compound, but that was not the case.
Is there a way of writing out the JSON file for each epoch?

**Comment by rwxayheee** [comment]
Hi @marco-chimfarm 

Thanks for your kind reply. It would be greatly appreciated if you could provide a little more information, such as the last logging information you got before hitting this error, and the full error message with its Traceback. 

I am one of the caretakers of [Meeko](https://github.com/forlilab/Meeko) that is listed as a dependency by project. I replied here as I was wondering if the JSON-related issue you encountered was on Meeko. 

But I also just realized that maize-contrib [requires a very early version (v0.4.0) of Meeko](https://github.com/MolecularAI/maize-contrib/blob/63c02de4393374a98b2d25b9944a26c2a64328c3/pyproject.toml#L19). So downgrading Meeko to 0.4.0 might be the first thing you could try. We have made some major refactoring since v0.4.0 including the functions that are related to JSON. Maybe it's some behavior change or we introduced a bug that broke maize-contrib. If so, feel free to post on our repository and we will take a look! 

If your workflow doesn't depend on Meeko, and you're still getting the errors, maybe the developer of this project can help you more. And again, if you provide some additional details (logging information, full error message with its Traceback, example files and commands to reproduce it) it would be really helpful
